/**
 * External assistant identities (CTOS-004 Part D/E/F) - see docs/MCP-BRIDGE.md.
 *
 * An ExternalClient is a registered outside assistant (ChatGPT, another Claude session, a future
 * automation) that reaches CT-OS only through the MCP tool layer (src/mcp/). This file owns:
 *   - creating/disabling/revoking/rotating a client identity (human-only - the same structural
 *     pattern as services/skills.ts#reviewSkill: an agent-shaped or external-shaped actor is
 *     rejected at the type level before any runtime check even runs);
 *   - hashing and verifying its local bearer token (the raw token is generated once, returned once,
 *     and never stored - only its SHA-256 hash and an 8-char prefix for UI identification);
 *   - the permission-ceiling and allow-list check every MCP tool call goes through
 *     (src/mcp/registry.ts calls `toolAllowed` before a tool ever touches OSData); and
 *   - appending to the append-only externalAccessLog (Part D/L's audit trail), capped so it cannot
 *     grow unbounded in the in-memory store.
 *
 * One deliberate exception to "human-only, admin-gated": `bootstrapLocalExternalClient` below is
 * NOT actor-gated. It exists solely for src/mcp/server.ts's local-dev startup path (Part E "local
 * token or local session mechanism"), where a Node process reads a token from `.env.local` and
 * needs to register the matching identity before any human session exists to gate it through. It
 * is never exported to, or reachable from, any MCP tool, and the running web app never calls it -
 * only src/mcp/server.ts does, once, at boot. See docs/MCP-BRIDGE.md "Local dev auth".
 */
import type { ExternalAccessLogEntry, ExternalAccessResult, ExternalClient, ExternalClientStatus, ExternalClientType, ExternalPermissionCeiling, OSData, PermissionLevel } from "@/data/types";
import { newId, nowIso } from "@/lib/core";
import { sha256Hex } from "@/lib/hash";

export const EXTERNAL_CLIENT_TYPE_LABELS: Record<ExternalClientType, string> = {
  chatgpt: "ChatGPT",
  claude: "Claude",
  automation: "Automation",
  other: "Other",
};

export const EXTERNAL_CLIENT_STATUS_LABELS: Record<ExternalClientStatus, string> = {
  ACTIVE: "Active",
  DISABLED: "Disabled",
  REVOKED: "Revoked",
};

export const EXTERNAL_CEILING_LABELS: Record<ExternalPermissionCeiling, string> = {
  READ_ONLY: "Read only",
  GREEN_WRITE: "Read + GREEN writes",
};

export const EXTERNAL_CLIENT_ADMIN_ROLES = ["ADMIN", "PRODUCTION_LEAD"] as const;

export class ExternalClientPolicyError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ExternalClientPolicyError";
  }
}

export type ExternalClientActor = { kind: "human"; name: string; id: string; role: "ADMIN" | "PRODUCTION_LEAD" | "TEAM_MEMBER" | "VIEWER" };

function requireAdmin(actor: ExternalClientActor): void {
  if (actor.kind !== "human") throw new ExternalClientPolicyError("Only a human may manage external assistant identities");
  if (!(EXTERNAL_CLIENT_ADMIN_ROLES as readonly string[]).includes(actor.role)) throw new ExternalClientPolicyError(`${actor.role} may not manage external assistant identities (Admin or Production Lead only)`);
}

/** `ctos_ext_<48 hex chars>` — generated client-side (browser crypto) or server-side (Node crypto), never logged. */
export function generateExternalClientToken(): string {
  const bytes = new Uint8Array(24);
  const c = (globalThis as { crypto?: Crypto }).crypto;
  if (c?.getRandomValues) c.getRandomValues(bytes);
  else for (let i = 0; i < bytes.length; i++) bytes[i] = Math.floor(Math.random() * 256);
  return `ctos_ext_${Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("")}`;
}

function hashToken(token: string): string {
  return sha256Hex(token);
}

export interface CreateExternalClientInput {
  name: string;
  type: ExternalClientType;
  permissionCeiling: ExternalPermissionCeiling;
  allowedTools?: string[] | null;
  /** Pre-generated by the caller (e.g. the Settings UI, via generateExternalClientToken()) so it can be
   *  shown once before dispatch. Falls back to generating one internally when omitted. */
  rawToken?: string;
  id?: string;
  at?: string;
}

export function createExternalClient(data: OSData, actor: ExternalClientActor, input: CreateExternalClientInput): { data: OSData; client: ExternalClient; rawToken: string } {
  requireAdmin(actor);
  const at = input.at ?? nowIso();
  const rawToken = input.rawToken ?? generateExternalClientToken();
  const client: ExternalClient = {
    id: input.id ?? newId("ext"),
    name: input.name,
    type: input.type,
    status: "ACTIVE",
    permissionCeiling: input.permissionCeiling,
    allowedTools: input.allowedTools ?? null,
    tokenHash: hashToken(rawToken),
    tokenPrefix: rawToken.slice(0, 8),
    createdById: actor.id,
    createdAt: at,
    updatedAt: at,
    lastUsedAt: null,
    revokedAt: null,
  };
  return { data: { ...data, externalClients: [...data.externalClients, client] }, client, rawToken };
}

export function setExternalClientStatus(data: OSData, actor: ExternalClientActor, clientId: string, status: Extract<ExternalClientStatus, "ACTIVE" | "DISABLED">): { data: OSData; client: ExternalClient } {
  requireAdmin(actor);
  const existing = data.externalClients.find((c) => c.id === clientId);
  if (!existing) throw new Error(`External client ${clientId} not found`);
  if (existing.status === "REVOKED") throw new ExternalClientPolicyError("A revoked external client cannot be re-enabled - create a new identity instead");
  const client: ExternalClient = { ...existing, status, updatedAt: nowIso() };
  return { data: { ...data, externalClients: data.externalClients.map((c) => (c.id === clientId ? client : c)) }, client };
}

export function revokeExternalClient(data: OSData, actor: ExternalClientActor, clientId: string): { data: OSData; client: ExternalClient } {
  requireAdmin(actor);
  const existing = data.externalClients.find((c) => c.id === clientId);
  if (!existing) throw new Error(`External client ${clientId} not found`);
  const at = nowIso();
  const client: ExternalClient = { ...existing, status: "REVOKED", tokenHash: null, updatedAt: at, revokedAt: at };
  return { data: { ...data, externalClients: data.externalClients.map((c) => (c.id === clientId ? client : c)) }, client };
}

export function rotateExternalClientToken(data: OSData, actor: ExternalClientActor, clientId: string, rawToken?: string): { data: OSData; client: ExternalClient; rawToken: string } {
  requireAdmin(actor);
  const existing = data.externalClients.find((c) => c.id === clientId);
  if (!existing) throw new Error(`External client ${clientId} not found`);
  if (existing.status === "REVOKED") throw new ExternalClientPolicyError("A revoked external client cannot be rotated - create a new identity instead");
  const token = rawToken ?? generateExternalClientToken();
  const client: ExternalClient = { ...existing, tokenHash: hashToken(token), tokenPrefix: token.slice(0, 8), updatedAt: nowIso() };
  return { data: { ...data, externalClients: data.externalClients.map((c) => (c.id === clientId ? client : c)) }, client, rawToken: token };
}

export function verifyExternalToken(data: OSData, rawToken: string | null | undefined): ExternalClient | null {
  if (!rawToken) return null;
  const hash = hashToken(rawToken);
  const client = data.externalClients.find((c) => c.tokenHash === hash);
  if (!client || client.status !== "ACTIVE") return null;
  return client;
}

export function recordClientUse(data: OSData, clientId: string, at = nowIso()): OSData {
  return { ...data, externalClients: data.externalClients.map((c) => (c.id === clientId ? { ...c, lastUsedAt: at } : c)) };
}

export function toolAllowed(client: ExternalClient, tool: string, toolCeiling: ExternalPermissionCeiling): boolean {
  if (client.status !== "ACTIVE") return false;
  if (client.allowedTools && !client.allowedTools.includes(tool)) return false;
  if (toolCeiling === "READ_ONLY") return true;
  return client.permissionCeiling === "GREEN_WRITE";
}

const MAX_ACCESS_LOG = 500;

export interface RecordAccessInput {
  externalClientId: string;
  externalClientName: string;
  tool: string;
  projectId?: string | null;
  ctosUserId?: string | null;
  requestedAction: string;
  permissionTier?: PermissionLevel | "READ" | null;
  result: ExternalAccessResult;
  reason?: string;
  createdIds?: string[];
  id?: string;
  at?: string;
}

export function recordExternalAccess(data: OSData, input: RecordAccessInput): { data: OSData; entry: ExternalAccessLogEntry } {
  const entry: ExternalAccessLogEntry = {
    id: input.id ?? newId("extlog"),
    at: input.at ?? nowIso(),
    externalClientId: input.externalClientId,
    externalClientName: input.externalClientName,
    tool: input.tool,
    projectId: input.projectId ?? null,
    ctosUserId: input.ctosUserId ?? null,
    requestedAction: input.requestedAction,
    permissionTier: input.permissionTier ?? null,
    result: input.result,
    reason: input.reason,
    createdIds: input.createdIds,
  };
  const externalAccessLog = [...data.externalAccessLog, entry].slice(-MAX_ACCESS_LOG);
  return { data: { ...data, externalAccessLog }, entry };
}

export interface BootstrapLocalClientInput {
  name: string;
  type: ExternalClientType;
  permissionCeiling: ExternalPermissionCeiling;
  rawToken: string;
  allowedTools?: string[] | null;
  id?: string;
  at?: string;
}

/**
 * Local-dev-only bootstrap: register an ExternalClient identity from a token supplied via server
 * environment (CTOS_MCP_TOKEN), not through the human-gated actions above. Called exactly once, at
 * MCP server startup (src/mcp/server.ts) - never from an MCP tool, never from the running CT-OS web
 * app. See docs/MCP-BRIDGE.md "Local dev auth" for why this exists and its limits.
 */
export function bootstrapLocalExternalClient(data: OSData, input: BootstrapLocalClientInput): { data: OSData; client: ExternalClient } {
  const at = input.at ?? nowIso();
  const client: ExternalClient = {
    id: input.id ?? newId("ext"),
    name: input.name,
    type: input.type,
    status: "ACTIVE",
    permissionCeiling: input.permissionCeiling,
    allowedTools: input.allowedTools ?? null,
    tokenHash: hashToken(input.rawToken),
    tokenPrefix: input.rawToken.slice(0, 8),
    createdById: null,
    createdAt: at,
    updatedAt: at,
    lastUsedAt: null,
    revokedAt: null,
  };
  return { data: { ...data, externalClients: [...data.externalClients, client] }, client };
}
