-- Creative Touch Website OS — CTOS-008J: explicit system reference seed
--
-- Installation-level data only: the canonical agent roster (ORCH + A01-A08), workflow gates,
-- skills/instruction packs, the integrations catalogue, the reusable section library, and
-- DOCTRINE-scope knowledge. Generated verbatim from src/data/seed.ts's `productionBootstrapData`
-- via scripts/generate-system-reference-seed.mjs — do not hand-edit; regenerate instead if the
-- canonical definitions in seed.ts change. Every value here is exactly what the app's own runtime
-- self-heal (CTOS-008H, SupabaseRepository.load()) would write using the same toRow() serializer —
-- this migration makes that install-time state explicit and idempotent rather than relying only on
-- a self-heal that runs on first authenticated load.
--
-- NEVER inserts: clients, projects, tickets, artifacts, QA, approvals, launch holds, activity,
-- AGENCY-scope knowledge, or any project/client-instance data. Nothing here touches those tables.
--
-- Idempotent: every statement is "insert ... on conflict (id) do nothing" — running this migration
-- any number of times, against a database that already has some or all of these rows (including
-- rows an operator has since edited), never duplicates a row and never overwrites an existing one.
-- No DELETE, no TRUNCATE, no UPDATE.

-- ---------------------------------------------------------------- agents (9 rows)
insert into agents (id, code, short_code, name, role, responsibilities, status, status_detail, current_project_id, current_ticket_id, last_run_at, outputs_produced, provider_policy, permission_level, required_capabilities, produces_artifact_types, consumes_artifact_types, can_execute_site_changes, created_at, updated_at, mission, exclusions, default_priority, instruction_pack_ids) values ('agent_orch', 'ORCH', 'ORCH', 'Conductor', 'Workflow coordination & human approval gates', '["Coordinates the complete workflow","Routes work to specialist agents","Enforces human approval gates","Never approves gates, performs AMBER/RED actions, or decides client scope"]'::jsonb, 'WAITING_APPROVAL', 'Human Review', NULL, NULL, NULL, 0, '{"preferred":"claude","fallbacks":["openai"],"reviewer":null}'::jsonb, 'AMBER', '["text","structured_output","long_context"]'::jsonb, '["project_brief","build_plan"]'::jsonb, '["research_report","site_blueprint","design_system","content_pack","build_report","qa_report","client_feedback"]'::jsonb, false, NULL, NULL, NULL, NULL, NULL, NULL) on conflict (id) do nothing;
insert into agents (id, code, short_code, name, role, responsibilities, status, status_detail, current_project_id, current_ticket_id, last_run_at, outputs_produced, provider_policy, permission_level, required_capabilities, produces_artifact_types, consumes_artifact_types, can_execute_site_changes, created_at, updated_at, mission, exclusions, default_priority, instruction_pack_ids) values ('agent_01', 'A01', '01', 'Discovery', 'Business, site and competitor intelligence', '["Business analysis","Existing-site audit","Competitor intelligence"]'::jsonb, 'IDLE', NULL, NULL, NULL, NULL, 1, '{"preferred":"gemini","fallbacks":["claude","openai"],"reviewer":null}'::jsonb, 'GREEN', '["text","structured_output","long_context"]'::jsonb, '["research_report"]'::jsonb, '["project_brief","client_feedback"]'::jsonb, false, NULL, NULL, NULL, NULL, NULL, NULL) on conflict (id) do nothing;
insert into agents (id, code, short_code, name, role, responsibilities, status, status_detail, current_project_id, current_ticket_id, last_run_at, outputs_produced, provider_policy, permission_level, required_capabilities, produces_artifact_types, consumes_artifact_types, can_execute_site_changes, created_at, updated_at, mission, exclusions, default_priority, instruction_pack_ids) values ('agent_02', 'A02', '02', 'Site Architect', 'Sitemap, site architecture, UX, journeys, conversion architecture, navigation, keyword-to-page strategy, catalogue/ecommerce architecture', '["Sitemap & site architecture","Customer journey & UX design","Conversion architecture","Navigation structure","Keyword-to-page strategy","Catalogue & ecommerce architecture","Information architecture"]'::jsonb, 'IDLE', NULL, NULL, NULL, NULL, 1, '{"preferred":"claude","fallbacks":["openai"],"reviewer":"gemini"}'::jsonb, 'GREEN', '["text","structured_output"]'::jsonb, '["site_blueprint"]'::jsonb, '["research_report","project_brief","client_feedback"]'::jsonb, false, NULL, NULL, 'Turn business and research context into an information architecture and conversion logic a builder can execute without guessing.', '["Never writes final page copy (Agent 04)","Never changes a live site"]'::jsonb, 'BALANCED', '["skill_ux_review_pack"]'::jsonb) on conflict (id) do nothing;
insert into agents (id, code, short_code, name, role, responsibilities, status, status_detail, current_project_id, current_ticket_id, last_run_at, outputs_produced, provider_policy, permission_level, required_capabilities, produces_artifact_types, consumes_artifact_types, can_execute_site_changes, created_at, updated_at, mission, exclusions, default_priority, instruction_pack_ids) values ('agent_03', 'A03', '03', 'Creative Director', 'Visual direction, layout system, design tokens, imagery — operates in DIRECTION, COMPOSITION, and VISUAL_REVIEW passes', '["DIRECTION pass: brand and competitive direction analysis","COMPOSITION pass: page composition and layout design","VISUAL_REVIEW pass: screenshot-based visual validation (requires real screenshots — never DOM or text crawl alone)","Design tokens","Imagery direction"]'::jsonb, 'IDLE', NULL, NULL, NULL, NULL, 1, '{"preferred":"claude","fallbacks":["openai","gemini"],"reviewer":null}'::jsonb, 'GREEN', '["text","structured_output","vision"]'::jsonb, '["design_system"]'::jsonb, '["site_blueprint","research_report","client_feedback"]'::jsonb, false, NULL, NULL, 'Set the visual direction, layout system and design tokens the build must follow — and judge whether a finished build reads as client-ready.', '["Never self-certifies its own visual QA verdict on someone else''s build (Agent 06 reviews)","Never writes Elementor/WordPress structure itself"]'::jsonb, 'QUALITY', '["skill_ct_visual_design"]'::jsonb) on conflict (id) do nothing;
insert into agents (id, code, short_code, name, role, responsibilities, status, status_detail, current_project_id, current_ticket_id, last_run_at, outputs_produced, provider_policy, permission_level, required_capabilities, produces_artifact_types, consumes_artifact_types, can_execute_site_changes, created_at, updated_at, mission, exclusions, default_priority, instruction_pack_ids) values ('agent_04', 'A04', '04', 'Content', 'Page copy, metadata, schema content, alt text, internal linking, brand voice', '["Page copy","Metadata (title, description, OG tags)","Schema content (structured data text)","Alt text for images","Internal linking","Brand voice consistency"]'::jsonb, 'IDLE', NULL, NULL, NULL, NULL, 1, '{"preferred":"claude","fallbacks":["openai"],"reviewer":null}'::jsonb, 'GREEN', '["text","structured_output","long_context"]'::jsonb, '["content_pack"]'::jsonb, '["site_blueprint","design_system","research_report"]'::jsonb, false, NULL, NULL, NULL, NULL, NULL, NULL) on conflict (id) do nothing;
insert into agents (id, code, short_code, name, role, responsibilities, status, status_detail, current_project_id, current_ticket_id, last_run_at, outputs_produced, provider_policy, permission_level, required_capabilities, produces_artifact_types, consumes_artifact_types, can_execute_site_changes, created_at, updated_at, mission, exclusions, default_priority, instruction_pack_ids) values ('agent_05', 'A05', '05', 'Builder', 'Technical implementation', '["Elementor global design system","Templates & pages","WooCommerce configuration","Build reports"]'::jsonb, 'IDLE', NULL, NULL, NULL, NULL, 16, '{"preferred":"claude","fallbacks":["openai"],"reviewer":null}'::jsonb, 'AMBER', '["text","structured_output","code"]'::jsonb, '["build_report"]'::jsonb, '["build_plan","design_system","content_pack","site_blueprint","qa_report"]'::jsonb, true, NULL, NULL, 'Implement the approved design system and content in Elementor/WordPress natively, editable-first, without private mutations no one else can maintain.', '["Never certifies its own visual quality (Agent 03/06 do)","Never activates a launch itself"]'::jsonb, 'BALANCED', '["skill_ct_elementor_builder"]'::jsonb) on conflict (id) do nothing;
insert into agents (id, code, short_code, name, role, responsibilities, status, status_detail, current_project_id, current_ticket_id, last_run_at, outputs_produced, provider_policy, permission_level, required_capabilities, produces_artifact_types, consumes_artifact_types, can_execute_site_changes, created_at, updated_at, mission, exclusions, default_priority, instruction_pack_ids) values ('agent_06', 'A06', '06', 'QA', 'Independent QA — technical, visual, responsive, journey, content, SEO, and launch-readiness evidence. Does not own or execute launch.', '["Technical QA","Visual QA","Responsive QA","Journey QA","Content QA","SEO QA","Launch-readiness evidence and audit","Defect detection and severity classification","Challenge prior agent claims"]'::jsonb, 'IDLE', NULL, NULL, NULL, NULL, 2, '{"preferred":"openai","fallbacks":["claude","gemini"],"reviewer":null}'::jsonb, 'GREEN', '["text","structured_output","vision","review"]'::jsonb, '["qa_report"]'::jsonb, '["build_report","site_blueprint","design_system","content_pack"]'::jsonb, false, NULL, NULL, 'Detect defects across every QA dimension and produce evidence of launch readiness — never owns or executes the launch itself.', '["Never executes or approves launch (Agent 07 owns launch runbook, humans approve)","Never certifies its own audit output without real evidence"]'::jsonb, NULL, NULL) on conflict (id) do nothing;
insert into agents (id, code, short_code, name, role, responsibilities, status, status_detail, current_project_id, current_ticket_id, last_run_at, outputs_produced, provider_policy, permission_level, required_capabilities, produces_artifact_types, consumes_artifact_types, can_execute_site_changes, created_at, updated_at, mission, exclusions, default_priority, instruction_pack_ids) values ('agent_07', 'A07', '07', 'Launch & Infrastructure', 'Launch runbook, infrastructure verification, migration/preflight preparation, hosting/domain/DNS readiness, backup/rollback, post-launch verification, controlled activation preparation', '["Launch runbook","Infrastructure verification","Migration and preflight preparation","Hosting, domain and DNS readiness","Backup and rollback readiness","Post-launch verification","Controlled activation preparation"]'::jsonb, 'IDLE', NULL, NULL, NULL, NULL, 0, '{"preferred":"claude","fallbacks":["openai"],"reviewer":null}'::jsonb, 'AMBER', '["text","structured_output","code"]'::jsonb, '["deployment_report"]'::jsonb, '["qa_report","build_report"]'::jsonb, true, NULL, NULL, 'Prepare and verify every infrastructure condition required for a safe launch — never autonomously executes RED actions (DNS, registrar, payment) without explicit human authorisation.', '["Never autonomously executes RED actions (DNS, nameservers, payment credentials, registrar) without explicit named human authorisation"]'::jsonb, NULL, NULL) on conflict (id) do nothing;
insert into agents (id, code, short_code, name, role, responsibilities, status, status_detail, current_project_id, current_ticket_id, last_run_at, outputs_produced, provider_policy, permission_level, required_capabilities, produces_artifact_types, consumes_artifact_types, can_execute_site_changes, created_at, updated_at, mission, exclusions, default_priority, instruction_pack_ids) values ('agent_08', 'A08', '08', 'Curator', 'Event-triggered or scheduled review of evidence — proposes lesson candidates, never runs continuously', '["Review client feedback (event-triggered on feedback receipt)","Review QA defects (event-triggered on QA run completion)","Identify successful & failed patterns (scheduled post-project review)","Review performance & conversion evidence (scheduled)","Propose lesson candidates"]'::jsonb, 'IDLE', NULL, NULL, NULL, NULL, 0, '{"preferred":"claude","fallbacks":["gemini","openai"],"reviewer":null}'::jsonb, 'GREEN', '["text","structured_output","long_context","review"]'::jsonb, '["lesson_candidate"]'::jsonb, '["qa_report","client_feedback","build_report","deployment_report","research_report"]'::jsonb, false, NULL, NULL, 'Turn scattered evidence (QA defects, client feedback, performance data) into proposed, evidence-backed lessons. Runs on trigger (feedback/QA events) or schedule (post-project) — never autonomously and continuously.', '["Never approves its own lesson proposals (a human always reviews)","Never builds or executes site changes","Never runs continuously — only on event trigger or schedule"]'::jsonb, 'QUALITY', NULL) on conflict (id) do nothing;

-- ---------------------------------------------------------------- gates (4 rows)
insert into gates (id, key, label, "order", requires_human_approval, required_artifact_types, confirm_on_open_holds, description) values ('gate_strategy', 'STRATEGY', 'Strategy', 1, true, '["research_report","site_blueprint"]'::jsonb, false, 'Human confirms the research and site blueprint before design starts.') on conflict (id) do nothing;
insert into gates (id, key, label, "order", requires_human_approval, required_artifact_types, confirm_on_open_holds, description) values ('gate_design', 'DESIGN', 'Design', 2, true, '["design_system"]'::jsonb, false, 'Human design approval of the visual direction and homepage preview.') on conflict (id) do nothing;
insert into gates (id, key, label, "order", requires_human_approval, required_artifact_types, confirm_on_open_holds, description) values ('gate_staging', 'STAGING_BUILD', 'Staging Build', 3, true, '["build_report","qa_report"]'::jsonb, false, 'Human accepts the staging build after QA and the regression audit.') on conflict (id) do nothing;
insert into gates (id, key, label, "order", requires_human_approval, required_artifact_types, confirm_on_open_holds, description) values ('gate_launch', 'LAUNCH', 'Launch', 4, true, '["qa_report"]'::jsonb, true, 'Human launch approval. Never auto-approves on zero QA counts; open holds require explicit acceptance.') on conflict (id) do nothing;

-- ---------------------------------------------------------------- skills (3 rows)
insert into skills (id, name, version, kind, status, scope, owner_agent_ids, reviewer_agent_ids, content, evidence, supersedes_id, approved_by, approved_by_id, approved_at, created_at, updated_at) values ('skill_ux_review_pack', 'UX & Conversion Review Checklist v1', 1, 'instruction_pack', 'APPROVED', 'agent-behaviour', '["agent_02"]'::jsonb, '["agent_06"]'::jsonb, 'Before proposing a sitemap or conversion journey: (1) every primary journey must resolve to one clear conversion goal — no page may leave the visitor without a next action; (2) IA depth stays at or under 3 clicks from home for any commercial page; (3) state the conversion logic in plain language a client can read, not just a diagram; (4) call out open questions explicitly rather than guessing at missing business context; (5) never propose a structure that requires a page type the build agent has not been given.', '["CTOS-003 seed — modelled on U-Proof site_blueprint reviews"]'::jsonb, NULL, 'Richard', NULL, NULL, NULL, NULL) on conflict (id) do nothing;
insert into skills (id, name, version, kind, status, scope, owner_agent_ids, reviewer_agent_ids, content, evidence, supersedes_id, approved_by, approved_by_id, approved_at, created_at, updated_at) values ('skill_ct_visual_design', 'CT Visual Design Skill v0.2', 2, 'design_review', 'CANDIDATE', 'design-review', '["agent_03"]'::jsonb, '["agent_06"]'::jsonb, '18-dimension structured visual review, never self-certified by the builder (A03 runs DIRECTION/COMPOSITION/VISUAL_REVIEW passes; A06 runs independent QA). Dimensions: BRAND_ALIGNMENT, VISUAL_HIERARCHY, LAYOUT_COMPOSITION, SPACING_RHYTHM, TYPOGRAPHY, COLOR_USE, IMAGERY, NAVIGATION, CTA_CLARITY, CONVERSION_CLARITY, TRUST, CONTENT_CLARITY, RESPONSIVENESS, MOBILE_USABILITY, PRODUCT_PRESENTATION, ORIGINALITY, POLISH, TECHNICAL_VISUAL_DEFECTS. Each dimension scored 1–5 and mapped to a verdict (A=4–5, B=3, C=1–2). Overall verdict uses priority order — any score ≤2 forces C, any score=3 forces B; no dimension averaging that hides a CRITICAL failure. Anti-generic rules enforced: no hero+3-cards commodity layouts; no generic icon sets as design features; no stock-photo hero images; no gradient-only buttons; no ''Why us?'' 3-icon grids; no footer-as-primary-navigation; no unverified counter badges (awards/years/etc). Screenshot evidence required at 1440px (desktop) and 375px (mobile) minimum before any review pass. All claims typed as OBSERVED/INFERRED/PROPOSED/VERIFIED — no evidence-free assertions. Evidence grounding: scores cite specific screenshot coordinates, section names, or element descriptions. Post-build gate sequence: BUILD → SCREENSHOT_CAPTURE → A03_VISUAL_REVIEW → A06_QA → HUMAN_APPROVAL → APPROVED.', '["U-Proof visual QA passes — desktop/tablet/mobile screenshot review","U-Proof product card legibility fixes","CTOS-005B 18-dimension rubric"]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL) on conflict (id) do nothing;
insert into skills (id, name, version, kind, status, scope, owner_agent_ids, reviewer_agent_ids, content, evidence, supersedes_id, approved_by, approved_by_id, approved_at, created_at, updated_at) values ('skill_ct_elementor_builder', 'CT Elementor Builder Skill v0.2', 2, 'build_practice', 'CANDIDATE', 'build-practice', '["agent_05"]'::jsonb, '["agent_06"]'::jsonb, 'Validated WordPress/Elementor implementation practice with build manifest governance (CTOS-005B): Build strategy per section: LIBRARY_ASSEMBLY (reuse approved section library pattern) or NATIVE_NOVEL_BUILD (new construction requiring noveltyJustification). LIBRARY_ASSEMBLY is the default — NATIVE_NOVEL_BUILD requires explicit written justification why no library pattern fits. Build manifest (elementor_build_manifest artifact) must record strategy, libraryEntryId, and humanEditProtection flag per section. humanEditProtection=true sections must not be overwritten by subsequent agent passes without human approval. Design tokens (color, typography, spacing) consumed from the active DesignTokenSet — no per-page overrides; required token kinds: color, typography, spacing. Build with native Elementor containers/widgets first — avoid giant custom HTML blobs; keep construction editable-first so a human can adjust it in the editor afterward; use the global Site Kit (colours, type, spacing) rather than per-page overrides; scope custom CSS narrowly and use custom JS only when a native option genuinely does not exist; any structured Elementor write (via the REST/DB layer) must be re-read and parsed immediately after writing, to confirm it saved as intended, not assumed from a 200 response; take a backup before any material mutation; wp_slash semantics differ between WP metadata APIs and raw DB writes — treat raw DB writes as a narrow fallback only, never the default path; verify Elementor page/template CSS actually propagated (not just that the save call succeeded); browser render validation is required — HTTP 200 is not visual QA; validate with real CDP viewport emulation at 1440/1254/1024/768/480/375; check shared header/footer consistency across templates; the builder never certifies its own final visual quality (Agent 03/06 do, via the CT Visual Design Skill); all work stays isolated from production until a human approves it, and every risky change has a stated rollback plan before it is made.', '["U-Proof Elementor build — global Site Kit usage","U-Proof structured write verification practice","CTOS-005B build manifest governance"]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL) on conflict (id) do nothing;

-- ---------------------------------------------------------------- integrations (11 rows)
insert into integrations (id, name, plane, purpose, status, provider_id, created_at, updated_at) values ('supabase', 'Supabase', 'control', 'Persistence, auth and realtime for the OS store.', 'NOT_CONNECTED', NULL, NULL, NULL) on conflict (id) do nothing;
insert into integrations (id, name, plane, purpose, status, provider_id, created_at, updated_at) values ('claude', 'Claude', 'intelligence', 'Intelligence provider (Anthropic). Replaceable per agent.', 'STUB', 'claude', NULL, NULL) on conflict (id) do nothing;
insert into integrations (id, name, plane, purpose, status, provider_id, created_at, updated_at) values ('openai', 'OpenAI', 'intelligence', 'Intelligence provider. Replaceable per agent.', 'STUB', 'openai', NULL, NULL) on conflict (id) do nothing;
insert into integrations (id, name, plane, purpose, status, provider_id, created_at, updated_at) values ('gemini', 'Gemini', 'intelligence', 'Intelligence provider (Google). Replaceable per agent.', 'STUB', 'gemini', NULL, NULL) on conflict (id) do nothing;
insert into integrations (id, name, plane, purpose, status, provider_id, created_at, updated_at) values ('orchestrator', 'AI Orchestrator', 'execution', 'Coordinates specialist agents and enforces approval gates.', 'FUTURE', NULL, NULL, NULL) on conflict (id) do nothing;
insert into integrations (id, name, plane, purpose, status, provider_id, created_at, updated_at) values ('wordpress-exec', 'WordPress execution', 'execution', 'Executes build tickets against staging via SSH + WP-CLI.', 'FUTURE', NULL, NULL, NULL) on conflict (id) do nothing;
insert into integrations (id, name, plane, purpose, status, provider_id, created_at, updated_at) values ('wordpress-mcp', 'WordPress MCP', 'execution', 'Structured read/write access to WordPress sites.', 'FUTURE', NULL, NULL, NULL) on conflict (id) do nothing;
insert into integrations (id, name, plane, purpose, status, provider_id, created_at, updated_at) values ('google', 'Google', 'execution', 'Search Console, Analytics, Tag Manager, Business Profile.', 'FUTURE', NULL, NULL, NULL) on conflict (id) do nothing;
insert into integrations (id, name, plane, purpose, status, provider_id, created_at, updated_at) values ('meta', 'Meta', 'execution', 'Pixel, domain verification, business assets.', 'FUTURE', NULL, NULL, NULL) on conflict (id) do nothing;
insert into integrations (id, name, plane, purpose, status, provider_id, created_at, updated_at) values ('cloudflare', 'Cloudflare', 'execution', 'DNS, proxy and SSL for client zones.', 'FUTURE', NULL, NULL, NULL) on conflict (id) do nothing;
insert into integrations (id, name, plane, purpose, status, provider_id, created_at, updated_at) values ('hosting', 'Hosting', 'execution', 'Company-controlled host: staging, backups, SSH.', 'FUTURE', NULL, NULL, NULL) on conflict (id) do nothing;

-- ---------------------------------------------------------------- section_library (15 rows)
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_hero_standard', '"Hero — Standard"'::jsonb, '"Full-width hero: H1 + subtext + single CTA, image right or background"'::jsonb, '"hero"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '["U-Proof homepage hero"]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_hero_split', '"Hero — Split"'::jsonb, '"50/50 hero: headline + CTA left, image right (no background)"'::jsonb, '"hero"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '[]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_feature_3col', '"Feature Row — 3 Column"'::jsonb, '"3-column icon/image + heading + body + optional CTA per card"'::jsonb, '"content"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '["U-Proof solutions row"]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_feature_2col', '"Feature Row — 2 Column"'::jsonb, '"2-column feature/comparison row"'::jsonb, '"content"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '[]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_cta_banner', '"CTA Banner"'::jsonb, '"Full-width or contained CTA strip: short headline + button"'::jsonb, '"conversion"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '["U-Proof contact CTA"]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_testimonials_row', '"Testimonials Row"'::jsonb, '"1–3 testimonial cards with quote, name and optional role/company"'::jsonb, '"trust"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '[]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_product_grid', '"Product Grid (WooCommerce)"'::jsonb, '"WooCommerce product archive grid — standard card layout"'::jsonb, '"ecommerce"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '["U-Proof Product Archive template 292"]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_product_card', '"Product Card (WooCommerce)"'::jsonb, '"Single WooCommerce product card — image + title + price + CTA"'::jsonb, '"ecommerce"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '["U-Proof Single Product template 293"]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_contact_form', '"Contact Form"'::jsonb, '"Contact form with name, email, message; optional phone"'::jsonb, '"forms"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '[]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_header_standard', '"Header — Standard"'::jsonb, '"Logo left; main nav; optional CTA button; hamburger on mobile"'::jsonb, '"layout"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '["U-Proof header"]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_footer_standard', '"Footer — Standard"'::jsonb, '"Logo; secondary nav; contact details; copyright; legal links"'::jsonb, '"layout"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '["U-Proof footer"]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_breadcrumb', '"Breadcrumb"'::jsonb, '"Standard breadcrumb trail for interior pages"'::jsonb, '"navigation"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '[]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_accordion_faq', '"Accordion / FAQ"'::jsonb, '"Expand-collapse FAQ or content accordion"'::jsonb, '"content"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '[]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_image_text_row', '"Image + Text Row"'::jsonb, '"Alternating image/text rows with optional CTA"'::jsonb, '"content"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '[]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;
insert into section_library (id, name, description, category, status, build_strategy, novelty_justification, evidence, approved_by, approved_at, created_at) values ('slib_content_richtext', '"Rich Text Content Block"'::jsonb, '"Full-width or contained WYSIWYG content block"'::jsonb, '"content"'::jsonb, '"CANDIDATE"'::jsonb, '"LIBRARY_ASSEMBLY"'::jsonb, NULL, '[]'::jsonb, NULL, NULL, NULL) on conflict (id) do nothing;

-- ---------------------------------------------------------------- knowledge_items (DOCTRINE only, 4 rows)
insert into knowledge_items (id, scope, category, title, content, evidence, confidence, status, project_id, job_id, proposed_by_agent_id, reviewed_by, reviewed_at, created_at, updated_at) values ('kn_doctrine_pipeline', 'DOCTRINE', 'safety', 'Every build passes through the safety pipeline', 'BUILD → PREVIEW → HUMAN DESIGN APPROVAL → QA → FINAL REGRESSION AUDIT → CONTROLLED ACTIVATION TESTING → HUMAN LAUNCH APPROVAL → LIVE. No stage may be skipped by an agent.', '["state-machine SAFETY_PIPELINE"]'::jsonb, 1, 'APPROVED', NULL, NULL, NULL, 'Production Lead', NULL, NULL, NULL) on conflict (id) do nothing;
insert into knowledge_items (id, scope, category, title, content, evidence, confidence, status, project_id, job_id, proposed_by_agent_id, reviewed_by, reviewed_at, created_at, updated_at) values ('kn_doctrine_permissions', 'DOCTRINE', 'safety', 'GREEN / AMBER / RED permission tiers', 'GREEN actions run automatically. AMBER actions require explicit human approval before execution. RED actions (DNS, registrar, payment credentials, destructive infrastructure) are never executed by an agent without explicit, named authorization.', '["state-machine PERMISSION_MODEL"]'::jsonb, 1, 'APPROVED', NULL, NULL, NULL, 'Production Lead', NULL, NULL, NULL) on conflict (id) do nothing;
insert into knowledge_items (id, scope, category, title, content, evidence, confidence, status, project_id, job_id, proposed_by_agent_id, reviewed_by, reviewed_at, created_at, updated_at) values ('kn_doctrine_launch', 'DOCTRINE', 'safety', 'Launch never auto-approves', 'QA at zero is necessary, never sufficient, for launch. Launch requires human approval; approving with open launch holds is a deliberate, recorded human decision.', '["state-machine SAFETY_PIPELINE — LAUNCH gate"]'::jsonb, 1, 'APPROVED', NULL, NULL, NULL, 'Production Lead', NULL, NULL, NULL) on conflict (id) do nothing;
insert into knowledge_items (id, scope, category, title, content, evidence, confidence, status, project_id, job_id, proposed_by_agent_id, reviewed_by, reviewed_at, created_at, updated_at) values ('kn_doctrine_learning', 'DOCTRINE', 'process', 'Agents propose; humans approve knowledge', 'Agents may propose lesson candidates. No agent may promote its own output into AGENCY or DOCTRINE knowledge. Human approval is the only path from CANDIDATE to APPROVED.', '["CTOS-001 Part F"]'::jsonb, 1, 'APPROVED', NULL, NULL, NULL, 'Production Lead', NULL, NULL, NULL) on conflict (id) do nothing;
