// Generated by scripts/bundle-vercel-functions.mjs — do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all2) => {
  for (var name in all2)
    __defProp(target, name, { get: all2[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// api-src/site-capture.ts
var site_capture_exports = {};
__export(site_capture_exports, {
  config: () => config,
  default: () => handler
});
module.exports = __toCommonJS(site_capture_exports);

// src/gateway/site-capture.ts
var import_promises = require("node:dns/promises");

// src/services/site-digest.ts
var LIMITS = { h1: 10, h2: 15, navLinks: 25, ctaTexts: 12, scriptHosts: 20, contactSignals: 10, excerptChars: 700 };
var ANALYTICS_PATTERNS = [/googletagmanager\.com/i, /google-analytics\.com/i, /gtag\(/i, /fbq\(/i, /connect\.facebook\.net/i, /hotjar/i, /_hjSettings/i, /clarity\.ms/i, /plausible\.io/i, /matomo/i];
var CTA_PATTERNS = [/get (a )?quote/i, /contact us/i, /book (now|a call|online)/i, /call (us|now)/i, /get started/i, /enquire/i, /request/i, /buy now/i, /add to cart/i, /shop now/i, /sign up/i, /subscribe/i, /learn more/i, /download/i, /apply/i];
function decodeEntities(s) {
  return s.replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n))).replace(/\s+/g, " ").trim();
}
function stripTags(html) {
  return decodeEntities(html.replace(/<[^>]+>/g, " "));
}
function all(re, html, max, map) {
  const out = [];
  let m;
  const g = new RegExp(re.source, re.flags.includes("g") ? re.flags : `${re.flags}g`);
  while ((m = g.exec(html)) && out.length < max) {
    const v = map(m);
    if (v) out.push(v);
  }
  return out;
}
function hostOf(src) {
  try {
    return new URL(src).hostname.toLowerCase();
  } catch {
    return null;
  }
}
function resolveHref(href, base) {
  const h = href.trim();
  if (!h || /^(#|javascript:|mailto:|tel:|data:)/i.test(h)) return null;
  try {
    const u = new URL(h, base);
    if (u.protocol !== "http:" && u.protocol !== "https:") return null;
    u.hash = "";
    return u.toString();
  } catch {
    return null;
  }
}
function digestPage(url, html, statusCode) {
  const head = html.slice(0, 2e5);
  const body = head.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<!--[\s\S]*?-->/g, " ");
  const title = decodeEntities(/<title[^>]*>([\s\S]*?)<\/title>/i.exec(head)?.[1] ?? "");
  const metaMatch = /<meta[^>]+name=["']description["'][^>]*content=["']([^"']*)["']/i.exec(head) ?? /<meta[^>]+content=["']([^"']*)["'][^>]*name=["']description["']/i.exec(head);
  const metaDescription = metaMatch ? decodeEntities(metaMatch[1]) || null : null;
  const h1 = all(/<h1[^>]*>([\s\S]*?)<\/h1>/i, body, LIMITS.h1, (m) => stripTags(m[1]) || null);
  const h2 = all(/<h2[^>]*>([\s\S]*?)<\/h2>/i, body, LIMITS.h2, (m) => stripTags(m[1]) || null);
  const anchorRe = /<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;
  const navLinks = [];
  const ctaTexts = [];
  const seenHref = /* @__PURE__ */ new Set();
  let am;
  while (am = anchorRe.exec(body)) {
    const text2 = stripTags(am[2]).slice(0, 80);
    const attrs = am[0];
    if (text2 && CTA_PATTERNS.some((p) => p.test(text2)) && ctaTexts.length < LIMITS.ctaTexts && !ctaTexts.includes(text2)) ctaTexts.push(text2);
    else if (/class=["'][^"']*\bbtn\b|button/i.test(attrs) && text2 && ctaTexts.length < LIMITS.ctaTexts && !ctaTexts.includes(text2)) ctaTexts.push(text2);
    const resolved = resolveHref(am[1], url);
    if (!resolved || !text2 || seenHref.has(resolved) || navLinks.length >= LIMITS.navLinks) continue;
    seenHref.add(resolved);
    navLinks.push({ text: text2, href: resolved });
  }
  for (const b of all(/<button[^>]*>([\s\S]*?)<\/button>/i, body, LIMITS.ctaTexts, (m) => stripTags(m[1]) || null)) {
    if (ctaTexts.length < LIMITS.ctaTexts && !ctaTexts.includes(b)) ctaTexts.push(b.slice(0, 80));
  }
  const formCount = (body.match(/<form\b/gi) ?? []).length;
  const imgTags = body.match(/<img\b[^>]*>/gi) ?? [];
  const imagesWithoutAlt = imgTags.filter((t) => !/\balt=["'][^"']+["']/i.test(t)).length;
  const scriptHosts = Array.from(new Set(all(/<script[^>]+src=["']([^"']+)["']/i, head, 200, (m) => hostOf(m[1])))).slice(0, LIMITS.scriptHosts);
  const hasAnalytics = ANALYTICS_PATTERNS.some((p) => p.test(head));
  const contactSignals = [];
  if (/href=["']tel:/i.test(body)) contactSignals.push("tel: link");
  if (/href=["']mailto:/i.test(body)) contactSignals.push("mailto: link");
  if (/\+\d[\d\s\-()]{7,}\d/.test(stripTags(body))) contactSignals.push("phone number in text");
  if (/whatsapp|wa\.me/i.test(body)) contactSignals.push("WhatsApp link");
  if (formCount > 0) contactSignals.push(`${formCount} form(s)`);
  if (/testimonial|review|trustpilot|rating/i.test(body)) contactSignals.push("testimonial/review markup");
  const text = stripTags(body.replace(/<\/(p|div|li|h[1-6]|section|article|footer|header|nav)>/gi, ". "));
  const wordCount = text ? text.split(/\s+/).filter(Boolean).length : 0;
  return {
    url,
    statusCode,
    title,
    metaDescription,
    h1,
    h2,
    navLinks,
    ctaTexts,
    formCount,
    imageCount: imgTags.length,
    imagesWithoutAlt,
    externalScriptHosts: scriptHosts,
    hasAnalytics,
    contactSignals: contactSignals.slice(0, LIMITS.contactSignals),
    wordCount,
    textExcerpt: text.slice(0, LIMITS.excerptChars)
  };
}
var INTENT_RULES = [
  { intent: "LOW", re: /privacy|terms|conditions|legal|cookie|disclaimer|login|log-in|sign-?in|account|register|cart|checkout|wishlist|sitemap/i },
  { intent: "HIGH", re: /service|product|shop|store|catalog|how-to-order|how to order|ordering|order-?process|about|our-company|our company|who-we-are|company|pric|plans|packages|contact|get-in-touch|enquir|quote/i },
  { intent: "MEDIUM", re: /project|portfolio|our-work|case-stud|gallery|faq|help|support|deliver|shipping|industr|sector|solution|team|testimonial|review|blog|news|resources/i }
];
var INTENT_SCORE = { HIGH: 3, MEDIUM: 2, UNKNOWN: 1, LOW: 0 };
function crawlIntent(link) {
  let path = link.href;
  try {
    path = decodeURIComponent(new URL(link.href).pathname);
  } catch {
  }
  const probe = `${path} ${link.text}`;
  for (const r of INTENT_RULES) if (r.re.test(probe)) return r.intent;
  return "UNKNOWN";
}
function discoveredSameSiteLinks(homepage) {
  let home;
  try {
    home = new URL(homepage.url);
  } catch {
    return [];
  }
  const seen = /* @__PURE__ */ new Set();
  return homepage.navLinks.filter((l) => {
    try {
      const u = new URL(l.href);
      const key = u.toString().replace(/\/$/, "");
      if (u.hostname.toLowerCase() !== home.hostname.toLowerCase()) return false;
      if (key === home.toString().replace(/\/$/, "")) return false;
      if (/\.(pdf|jpg|jpeg|png|gif|svg|zip|mp4|webp|docx?|xlsx?)$/i.test(u.pathname)) return false;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    } catch {
      return false;
    }
  });
}
function pickCrawlLinks(homepage, max = 5) {
  return discoveredSameSiteLinks(homepage).map((l, index) => ({ href: l.href, score: INTENT_SCORE[crawlIntent(l)], index })).sort((a, b) => b.score - a.score || a.index - b.index).slice(0, Math.max(0, max)).map((l) => l.href);
}

// src/gateway/site-capture.ts
var MAX_PAGES = 6;
var MAX_HTML_BYTES = 15e5;
var FETCH_TIMEOUT_MS = 15e3;
var MAX_REDIRECTS = 5;
function isPrivateIPv4(ip) {
  const p = ip.split(".").map(Number);
  if (p.length !== 4 || p.some((n) => Number.isNaN(n))) return true;
  const [a, b] = p;
  return a === 0 || a === 10 || a === 127 || a === 100 && b >= 64 && b <= 127 || a === 169 && b === 254 || a === 172 && b >= 16 && b <= 31 || a === 192 && b === 168 || a === 192 && b === 0 || a >= 224;
}
function isPrivateIPv6(ip) {
  const v = ip.toLowerCase().replace(/^\[|\]$/g, "");
  if (v === "::" || v === "::1") return true;
  if (/^::ffff:(\d+\.\d+\.\d+\.\d+)$/.test(v)) return isPrivateIPv4(v.replace(/^::ffff:/, ""));
  return /^(fc|fd|fe[89ab])/.test(v);
}
function hostnameBlocked(url) {
  let parsed;
  try {
    parsed = new URL(url);
  } catch {
    return "Invalid URL";
  }
  if (parsed.protocol !== "https:" && parsed.protocol !== "http:") return `Protocol not allowed: ${parsed.protocol}`;
  if (parsed.username || parsed.password) return "Credentials in URL are not allowed";
  const h = parsed.hostname.toLowerCase();
  if (!h) return "Missing hostname";
  if (h === "localhost" || h.endsWith(".localhost") || h.endsWith(".local") || h.endsWith(".internal")) return "Loopback/internal hostnames are not allowed";
  if (h.startsWith("[")) return isPrivateIPv6(h) ? "Private IPv6 addresses are not allowed" : null;
  if (/^\d+$/.test(h) || /^0x/i.test(h) || /^\d+\.\d+\.\d+\.\d+$/.test(h) === false && /^[\d.]+$/.test(h)) return "Numeric hostnames are not allowed";
  if (/^\d+\.\d+\.\d+\.\d+$/.test(h)) return isPrivateIPv4(h) ? "Private network addresses are not allowed" : null;
  if (h === "metadata.google.internal" || h === "169.254.169.254") return "Metadata endpoint addresses are not allowed";
  if (!h.includes(".")) return "Single-label hostnames are not allowed";
  return null;
}
async function resolvedBlocked(url) {
  const h = new URL(url).hostname.toLowerCase();
  if (/^\d+\.\d+\.\d+\.\d+$/.test(h) || h.startsWith("[")) return null;
  try {
    const addrs = await (0, import_promises.lookup)(h, { all: true });
    if (!addrs.length) return "Hostname did not resolve";
    for (const a of addrs) {
      if (a.family === 4 && isPrivateIPv4(a.address)) return `Hostname resolves to a private address (${a.address})`;
      if (a.family === 6 && isPrivateIPv6(a.address)) return `Hostname resolves to a private address (${a.address})`;
    }
    return null;
  } catch {
    return "Hostname could not be resolved";
  }
}
async function ssrfCheck(url) {
  return hostnameBlocked(url) ?? await resolvedBlocked(url);
}
async function fetchPublic(url) {
  let current = url;
  for (let hop = 0; hop <= MAX_REDIRECTS; hop++) {
    const blocked = await ssrfCheck(current);
    if (blocked) return { error: hop === 0 ? blocked : `Redirect target blocked: ${blocked}` };
    let res;
    try {
      res = await fetch(current, {
        signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
        headers: { "User-Agent": "CT-OS-Audit/1.0 (public website analysis; contact@creativetouch.co.za)", Accept: "text/html,application/xhtml+xml" },
        redirect: "manual",
        credentials: "omit"
      });
    } catch (err) {
      return { error: err instanceof Error ? err.message : String(err) };
    }
    if (res.status >= 300 && res.status < 400) {
      const loc = res.headers.get("location");
      if (!loc) return { error: `Redirect (${res.status}) without location` };
      try {
        current = new URL(loc, current).toString();
      } catch {
        return { error: "Invalid redirect location" };
      }
      continue;
    }
    const type = res.headers.get("content-type") ?? "";
    if (!/text\/html|application\/xhtml/i.test(type) && type) return { error: `Not an HTML page (${type.split(";")[0]})` };
    const declared = Number(res.headers.get("content-length") ?? "0");
    if (declared > MAX_HTML_BYTES) return { error: `Response too large (${declared} bytes)` };
    const reader = res.body?.getReader();
    if (!reader) return { finalUrl: current, status: res.status, html: "" };
    const decoder = new TextDecoder();
    let html = "";
    let total = 0;
    while (total < MAX_HTML_BYTES) {
      const { done, value } = await reader.read();
      if (done) break;
      total += value.byteLength;
      html += decoder.decode(value, { stream: true });
    }
    reader.cancel().catch(() => void 0);
    return { finalUrl: current, status: res.status, html };
  }
  return { error: `Too many redirects (>${MAX_REDIRECTS})` };
}
async function captureSite(url, maxPages = MAX_PAGES) {
  const blocked = await ssrfCheck(url);
  if (blocked) return { ok: false, reason: blocked, blocked: true };
  const capturedAt = (/* @__PURE__ */ new Date()).toISOString();
  const home = await fetchPublic(url);
  if ("error" in home) return { ok: false, error: home.error };
  if (home.status >= 400) return { ok: false, error: `Homepage returned HTTP ${home.status}` };
  const homeDigest = digestPage(home.finalUrl, home.html, home.status);
  const pages = [homeDigest];
  const skippedUrls = [];
  const discoveredUrls = discoveredSameSiteLinks(homeDigest).map((l) => l.href);
  for (const link of pickCrawlLinks(homeDigest, Math.max(0, maxPages - 1))) {
    const r = await fetchPublic(link);
    if ("error" in r) {
      skippedUrls.push({ url: link, reason: r.error });
      continue;
    }
    if (r.status >= 400) {
      skippedUrls.push({ url: link, reason: `HTTP ${r.status}` });
      continue;
    }
    pages.push(digestPage(r.finalUrl, r.html, r.status));
  }
  return { ok: true, capture: { targetUrl: home.finalUrl, capturedAt, pages, skippedUrls, screenshots: [], discoveredUrls } };
}

// api-src/site-capture.ts
var config = { runtime: "nodejs" };
function readJson(req) {
  return new Promise((resolve) => {
    let raw = "";
    req.on("data", (c) => {
      raw += c.toString();
    });
    req.on("end", () => {
      try {
        resolve(raw ? JSON.parse(raw) : null);
      } catch {
        resolve(null);
      }
    });
    req.on("error", () => resolve(null));
  });
}
async function handler(req, res) {
  if (req.method !== "POST") {
    res.writeHead(405, { "content-type": "application/json" });
    res.end(JSON.stringify({ ok: false, reason: "Method not allowed" }));
    return;
  }
  try {
    const body = await readJson(req);
    const url = typeof body?.url === "string" ? body.url.trim() : null;
    if (!url) {
      res.writeHead(400, { "content-type": "application/json" });
      res.end(JSON.stringify({ ok: false, reason: "url is required" }));
      return;
    }
    const maxPages = Math.min(MAX_PAGES, Math.max(1, Number(body?.maxPages ?? MAX_PAGES) || MAX_PAGES));
    const result = await captureSite(url, maxPages);
    if (!result.ok && "blocked" in result && result.blocked) {
      res.writeHead(403, { "content-type": "application/json" });
      res.end(JSON.stringify(result));
      return;
    }
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify(result));
  } catch (err) {
    res.writeHead(500, { "content-type": "application/json" });
    res.end(JSON.stringify({ ok: false, reason: err instanceof Error ? err.message : String(err) }));
  }
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  config
});
